//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RedSky.Infrastructure.NFSe.SPTatuiNFSeRecepcionarLoteRPSSincrono {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="Abrasf2", ConfigurationName="SPTatuiNFSeRecepcionarLoteRPSSincrono.RecepcionarLoteRpsSincronoSoapPort")]
    public interface RecepcionarLoteRpsSincronoSoapPort {
        
        // CODEGEN: Generating message contract since the wrapper name (RecepcionarLoteRpsSincrono.Execute) of message ExecuteRequest does not match the default value (Execute)
        [System.ServiceModel.OperationContractAttribute(Action="Abrasf2action/ARECEPCIONARLOTERPSSINCRONO.Execute", ReplyAction="*")]
        RedSky.Infrastructure.NFSe.SPTatuiNFSeRecepcionarLoteRPSSincrono.ExecuteResponse Execute(RedSky.Infrastructure.NFSe.SPTatuiNFSeRecepcionarLoteRPSSincrono.ExecuteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="Abrasf2action/ARECEPCIONARLOTERPSSINCRONO.Execute", ReplyAction="*")]
        System.Threading.Tasks.Task<RedSky.Infrastructure.NFSe.SPTatuiNFSeRecepcionarLoteRPSSincrono.ExecuteResponse> ExecuteAsync(RedSky.Infrastructure.NFSe.SPTatuiNFSeRecepcionarLoteRPSSincrono.ExecuteRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RecepcionarLoteRpsSincrono.Execute", WrapperNamespace="Abrasf2", IsWrapped=true)]
    public partial class ExecuteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="Abrasf2", Order=0)]
        public string Entrada;
        
        public ExecuteRequest() {
        }
        
        public ExecuteRequest(string Entrada) {
            this.Entrada = Entrada;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RecepcionarLoteRpsSincrono.ExecuteResponse", WrapperNamespace="Abrasf2", IsWrapped=true)]
    public partial class ExecuteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="Abrasf2", Order=0)]
        public string Resposta;
        
        public ExecuteResponse() {
        }
        
        public ExecuteResponse(string Resposta) {
            this.Resposta = Resposta;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface RecepcionarLoteRpsSincronoSoapPortChannel : RedSky.Infrastructure.NFSe.SPTatuiNFSeRecepcionarLoteRPSSincrono.RecepcionarLoteRpsSincronoSoapPort, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RecepcionarLoteRpsSincronoSoapPortClient : System.ServiceModel.ClientBase<RedSky.Infrastructure.NFSe.SPTatuiNFSeRecepcionarLoteRPSSincrono.RecepcionarLoteRpsSincronoSoapPort>, RedSky.Infrastructure.NFSe.SPTatuiNFSeRecepcionarLoteRPSSincrono.RecepcionarLoteRpsSincronoSoapPort {
        
        public RecepcionarLoteRpsSincronoSoapPortClient() {
        }
        
        public RecepcionarLoteRpsSincronoSoapPortClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RecepcionarLoteRpsSincronoSoapPortClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RecepcionarLoteRpsSincronoSoapPortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RecepcionarLoteRpsSincronoSoapPortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RedSky.Infrastructure.NFSe.SPTatuiNFSeRecepcionarLoteRPSSincrono.ExecuteResponse RedSky.Infrastructure.NFSe.SPTatuiNFSeRecepcionarLoteRPSSincrono.RecepcionarLoteRpsSincronoSoapPort.Execute(RedSky.Infrastructure.NFSe.SPTatuiNFSeRecepcionarLoteRPSSincrono.ExecuteRequest request) {
            return base.Channel.Execute(request);
        }
        
        public string Execute(string Entrada) {
            RedSky.Infrastructure.NFSe.SPTatuiNFSeRecepcionarLoteRPSSincrono.ExecuteRequest inValue = new RedSky.Infrastructure.NFSe.SPTatuiNFSeRecepcionarLoteRPSSincrono.ExecuteRequest();
            inValue.Entrada = Entrada;
            RedSky.Infrastructure.NFSe.SPTatuiNFSeRecepcionarLoteRPSSincrono.ExecuteResponse retVal = ((RedSky.Infrastructure.NFSe.SPTatuiNFSeRecepcionarLoteRPSSincrono.RecepcionarLoteRpsSincronoSoapPort)(this)).Execute(inValue);
            return retVal.Resposta;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RedSky.Infrastructure.NFSe.SPTatuiNFSeRecepcionarLoteRPSSincrono.ExecuteResponse> RedSky.Infrastructure.NFSe.SPTatuiNFSeRecepcionarLoteRPSSincrono.RecepcionarLoteRpsSincronoSoapPort.ExecuteAsync(RedSky.Infrastructure.NFSe.SPTatuiNFSeRecepcionarLoteRPSSincrono.ExecuteRequest request) {
            return base.Channel.ExecuteAsync(request);
        }
        
        public System.Threading.Tasks.Task<RedSky.Infrastructure.NFSe.SPTatuiNFSeRecepcionarLoteRPSSincrono.ExecuteResponse> ExecuteAsync(string Entrada) {
            RedSky.Infrastructure.NFSe.SPTatuiNFSeRecepcionarLoteRPSSincrono.ExecuteRequest inValue = new RedSky.Infrastructure.NFSe.SPTatuiNFSeRecepcionarLoteRPSSincrono.ExecuteRequest();
            inValue.Entrada = Entrada;
            return ((RedSky.Infrastructure.NFSe.SPTatuiNFSeRecepcionarLoteRPSSincrono.RecepcionarLoteRpsSincronoSoapPort)(this)).ExecuteAsync(inValue);
        }
    }
}
