//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RedSky.Infrastructure.NFSe.SPSorocabaNFSe {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.issdigitalsod.com.br/WsNFe2/LoteRps.jws", ConfigurationName="SPSorocabaNFSe.LoteRps")]
    public interface LoteRps {
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://proces.wsnfe2.dsfnet.com.br) of message consultarSequencialRpsRequest does not match the default value (http://www.issdigitalsod.com.br/WsNFe2/LoteRps.jws)
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        RedSky.Infrastructure.NFSe.SPSorocabaNFSe.consultarSequencialRpsResponse consultarSequencialRps(RedSky.Infrastructure.NFSe.SPSorocabaNFSe.consultarSequencialRpsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<RedSky.Infrastructure.NFSe.SPSorocabaNFSe.consultarSequencialRpsResponse> consultarSequencialRpsAsync(RedSky.Infrastructure.NFSe.SPSorocabaNFSe.consultarSequencialRpsRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://proces.wsnfe2.dsfnet.com.br) of message enviarSincronoRequest does not match the default value (http://www.issdigitalsod.com.br/WsNFe2/LoteRps.jws)
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        RedSky.Infrastructure.NFSe.SPSorocabaNFSe.enviarSincronoResponse enviarSincrono(RedSky.Infrastructure.NFSe.SPSorocabaNFSe.enviarSincronoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<RedSky.Infrastructure.NFSe.SPSorocabaNFSe.enviarSincronoResponse> enviarSincronoAsync(RedSky.Infrastructure.NFSe.SPSorocabaNFSe.enviarSincronoRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://proces.wsnfe2.dsfnet.com.br) of message enviarRequest does not match the default value (http://www.issdigitalsod.com.br/WsNFe2/LoteRps.jws)
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        RedSky.Infrastructure.NFSe.SPSorocabaNFSe.enviarResponse enviar(RedSky.Infrastructure.NFSe.SPSorocabaNFSe.enviarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<RedSky.Infrastructure.NFSe.SPSorocabaNFSe.enviarResponse> enviarAsync(RedSky.Infrastructure.NFSe.SPSorocabaNFSe.enviarRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://proces.wsnfe2.dsfnet.com.br) of message testeEnviarRequest does not match the default value (http://www.issdigitalsod.com.br/WsNFe2/LoteRps.jws)
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        RedSky.Infrastructure.NFSe.SPSorocabaNFSe.testeEnviarResponse testeEnviar(RedSky.Infrastructure.NFSe.SPSorocabaNFSe.testeEnviarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<RedSky.Infrastructure.NFSe.SPSorocabaNFSe.testeEnviarResponse> testeEnviarAsync(RedSky.Infrastructure.NFSe.SPSorocabaNFSe.testeEnviarRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://proces.wsnfe2.dsfnet.com.br) of message consultarLoteRequest does not match the default value (http://www.issdigitalsod.com.br/WsNFe2/LoteRps.jws)
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        RedSky.Infrastructure.NFSe.SPSorocabaNFSe.consultarLoteResponse consultarLote(RedSky.Infrastructure.NFSe.SPSorocabaNFSe.consultarLoteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<RedSky.Infrastructure.NFSe.SPSorocabaNFSe.consultarLoteResponse> consultarLoteAsync(RedSky.Infrastructure.NFSe.SPSorocabaNFSe.consultarLoteRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://proces.wsnfe2.dsfnet.com.br) of message consultarAliquotaSimplesNacionalRequest does not match the default value (http://www.issdigitalsod.com.br/WsNFe2/LoteRps.jws)
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        RedSky.Infrastructure.NFSe.SPSorocabaNFSe.consultarAliquotaSimplesNacionalResponse consultarAliquotaSimplesNacional(RedSky.Infrastructure.NFSe.SPSorocabaNFSe.consultarAliquotaSimplesNacionalRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<RedSky.Infrastructure.NFSe.SPSorocabaNFSe.consultarAliquotaSimplesNacionalResponse> consultarAliquotaSimplesNacionalAsync(RedSky.Infrastructure.NFSe.SPSorocabaNFSe.consultarAliquotaSimplesNacionalRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://proces.wsnfe2.dsfnet.com.br) of message consultarNotaTomadaRequest does not match the default value (http://www.issdigitalsod.com.br/WsNFe2/LoteRps.jws)
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        RedSky.Infrastructure.NFSe.SPSorocabaNFSe.consultarNotaTomadaResponse consultarNotaTomada(RedSky.Infrastructure.NFSe.SPSorocabaNFSe.consultarNotaTomadaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<RedSky.Infrastructure.NFSe.SPSorocabaNFSe.consultarNotaTomadaResponse> consultarNotaTomadaAsync(RedSky.Infrastructure.NFSe.SPSorocabaNFSe.consultarNotaTomadaRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://proces.wsnfe2.dsfnet.com.br) of message consultarNotaRequest does not match the default value (http://www.issdigitalsod.com.br/WsNFe2/LoteRps.jws)
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        RedSky.Infrastructure.NFSe.SPSorocabaNFSe.consultarNotaResponse consultarNota(RedSky.Infrastructure.NFSe.SPSorocabaNFSe.consultarNotaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<RedSky.Infrastructure.NFSe.SPSorocabaNFSe.consultarNotaResponse> consultarNotaAsync(RedSky.Infrastructure.NFSe.SPSorocabaNFSe.consultarNotaRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://proces.wsnfe2.dsfnet.com.br) of message cancelarRequest does not match the default value (http://www.issdigitalsod.com.br/WsNFe2/LoteRps.jws)
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        RedSky.Infrastructure.NFSe.SPSorocabaNFSe.cancelarResponse cancelar(RedSky.Infrastructure.NFSe.SPSorocabaNFSe.cancelarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<RedSky.Infrastructure.NFSe.SPSorocabaNFSe.cancelarResponse> cancelarAsync(RedSky.Infrastructure.NFSe.SPSorocabaNFSe.cancelarRequest request);
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://proces.wsnfe2.dsfnet.com.br) of message consultarNFSeRpsRequest does not match the default value (http://www.issdigitalsod.com.br/WsNFe2/LoteRps.jws)
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        RedSky.Infrastructure.NFSe.SPSorocabaNFSe.consultarNFSeRpsResponse consultarNFSeRps(RedSky.Infrastructure.NFSe.SPSorocabaNFSe.consultarNFSeRpsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<RedSky.Infrastructure.NFSe.SPSorocabaNFSe.consultarNFSeRpsResponse> consultarNFSeRpsAsync(RedSky.Infrastructure.NFSe.SPSorocabaNFSe.consultarNFSeRpsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="consultarSequencialRps", WrapperNamespace="http://proces.wsnfe2.dsfnet.com.br", IsWrapped=true)]
    public partial class consultarSequencialRpsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string mensagemXml;
        
        public consultarSequencialRpsRequest() {
        }
        
        public consultarSequencialRpsRequest(string mensagemXml) {
            this.mensagemXml = mensagemXml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="consultarSequencialRpsResponse", WrapperNamespace="http://www.issdigitalsod.com.br/WsNFe2/LoteRps.jws", IsWrapped=true)]
    public partial class consultarSequencialRpsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string consultarSequencialRpsReturn;
        
        public consultarSequencialRpsResponse() {
        }
        
        public consultarSequencialRpsResponse(string consultarSequencialRpsReturn) {
            this.consultarSequencialRpsReturn = consultarSequencialRpsReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="enviarSincrono", WrapperNamespace="http://proces.wsnfe2.dsfnet.com.br", IsWrapped=true)]
    public partial class enviarSincronoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string mensagemXml;
        
        public enviarSincronoRequest() {
        }
        
        public enviarSincronoRequest(string mensagemXml) {
            this.mensagemXml = mensagemXml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="enviarSincronoResponse", WrapperNamespace="http://www.issdigitalsod.com.br/WsNFe2/LoteRps.jws", IsWrapped=true)]
    public partial class enviarSincronoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string enviarSincronoReturn;
        
        public enviarSincronoResponse() {
        }
        
        public enviarSincronoResponse(string enviarSincronoReturn) {
            this.enviarSincronoReturn = enviarSincronoReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="enviar", WrapperNamespace="http://proces.wsnfe2.dsfnet.com.br", IsWrapped=true)]
    public partial class enviarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string mensagemXml;
        
        public enviarRequest() {
        }
        
        public enviarRequest(string mensagemXml) {
            this.mensagemXml = mensagemXml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="enviarResponse", WrapperNamespace="http://www.issdigitalsod.com.br/WsNFe2/LoteRps.jws", IsWrapped=true)]
    public partial class enviarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string enviarReturn;
        
        public enviarResponse() {
        }
        
        public enviarResponse(string enviarReturn) {
            this.enviarReturn = enviarReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="testeEnviar", WrapperNamespace="http://proces.wsnfe2.dsfnet.com.br", IsWrapped=true)]
    public partial class testeEnviarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string mensagemXml;
        
        public testeEnviarRequest() {
        }
        
        public testeEnviarRequest(string mensagemXml) {
            this.mensagemXml = mensagemXml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="testeEnviarResponse", WrapperNamespace="http://www.issdigitalsod.com.br/WsNFe2/LoteRps.jws", IsWrapped=true)]
    public partial class testeEnviarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string testeEnviarReturn;
        
        public testeEnviarResponse() {
        }
        
        public testeEnviarResponse(string testeEnviarReturn) {
            this.testeEnviarReturn = testeEnviarReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="consultarLote", WrapperNamespace="http://proces.wsnfe2.dsfnet.com.br", IsWrapped=true)]
    public partial class consultarLoteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string mensagemXml;
        
        public consultarLoteRequest() {
        }
        
        public consultarLoteRequest(string mensagemXml) {
            this.mensagemXml = mensagemXml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="consultarLoteResponse", WrapperNamespace="http://www.issdigitalsod.com.br/WsNFe2/LoteRps.jws", IsWrapped=true)]
    public partial class consultarLoteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string consultarLoteReturn;
        
        public consultarLoteResponse() {
        }
        
        public consultarLoteResponse(string consultarLoteReturn) {
            this.consultarLoteReturn = consultarLoteReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="consultarAliquotaSimplesNacional", WrapperNamespace="http://proces.wsnfe2.dsfnet.com.br", IsWrapped=true)]
    public partial class consultarAliquotaSimplesNacionalRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string cpfResponsavel;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string ultimaAtualizacao;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        public string codCid;
        
        public consultarAliquotaSimplesNacionalRequest() {
        }
        
        public consultarAliquotaSimplesNacionalRequest(string cpfResponsavel, string ultimaAtualizacao, string codCid) {
            this.cpfResponsavel = cpfResponsavel;
            this.ultimaAtualizacao = ultimaAtualizacao;
            this.codCid = codCid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="consultarAliquotaSimplesNacionalResponse", WrapperNamespace="http://www.issdigitalsod.com.br/WsNFe2/LoteRps.jws", IsWrapped=true)]
    public partial class consultarAliquotaSimplesNacionalResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string consultarAliquotaSimplesNacionalReturn;
        
        public consultarAliquotaSimplesNacionalResponse() {
        }
        
        public consultarAliquotaSimplesNacionalResponse(string consultarAliquotaSimplesNacionalReturn) {
            this.consultarAliquotaSimplesNacionalReturn = consultarAliquotaSimplesNacionalReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="consultarNotaTomada", WrapperNamespace="http://proces.wsnfe2.dsfnet.com.br", IsWrapped=true)]
    public partial class consultarNotaTomadaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string mensagemXml;
        
        public consultarNotaTomadaRequest() {
        }
        
        public consultarNotaTomadaRequest(string mensagemXml) {
            this.mensagemXml = mensagemXml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="consultarNotaTomadaResponse", WrapperNamespace="http://www.issdigitalsod.com.br/WsNFe2/LoteRps.jws", IsWrapped=true)]
    public partial class consultarNotaTomadaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string consultarNotaTomadaReturn;
        
        public consultarNotaTomadaResponse() {
        }
        
        public consultarNotaTomadaResponse(string consultarNotaTomadaReturn) {
            this.consultarNotaTomadaReturn = consultarNotaTomadaReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="consultarNota", WrapperNamespace="http://proces.wsnfe2.dsfnet.com.br", IsWrapped=true)]
    public partial class consultarNotaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string mensagemXml;
        
        public consultarNotaRequest() {
        }
        
        public consultarNotaRequest(string mensagemXml) {
            this.mensagemXml = mensagemXml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="consultarNotaResponse", WrapperNamespace="http://www.issdigitalsod.com.br/WsNFe2/LoteRps.jws", IsWrapped=true)]
    public partial class consultarNotaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string consultarNotaReturn;
        
        public consultarNotaResponse() {
        }
        
        public consultarNotaResponse(string consultarNotaReturn) {
            this.consultarNotaReturn = consultarNotaReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="cancelar", WrapperNamespace="http://proces.wsnfe2.dsfnet.com.br", IsWrapped=true)]
    public partial class cancelarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string mensagemXml;
        
        public cancelarRequest() {
        }
        
        public cancelarRequest(string mensagemXml) {
            this.mensagemXml = mensagemXml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="cancelarResponse", WrapperNamespace="http://www.issdigitalsod.com.br/WsNFe2/LoteRps.jws", IsWrapped=true)]
    public partial class cancelarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string cancelarReturn;
        
        public cancelarResponse() {
        }
        
        public cancelarResponse(string cancelarReturn) {
            this.cancelarReturn = cancelarReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="consultarNFSeRps", WrapperNamespace="http://proces.wsnfe2.dsfnet.com.br", IsWrapped=true)]
    public partial class consultarNFSeRpsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string mensagemXml;
        
        public consultarNFSeRpsRequest() {
        }
        
        public consultarNFSeRpsRequest(string mensagemXml) {
            this.mensagemXml = mensagemXml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="consultarNFSeRpsResponse", WrapperNamespace="http://www.issdigitalsod.com.br/WsNFe2/LoteRps.jws", IsWrapped=true)]
    public partial class consultarNFSeRpsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string consultarNFSeRpsReturn;
        
        public consultarNFSeRpsResponse() {
        }
        
        public consultarNFSeRpsResponse(string consultarNFSeRpsReturn) {
            this.consultarNFSeRpsReturn = consultarNFSeRpsReturn;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface LoteRpsChannel : RedSky.Infrastructure.NFSe.SPSorocabaNFSe.LoteRps, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LoteRpsClient : System.ServiceModel.ClientBase<RedSky.Infrastructure.NFSe.SPSorocabaNFSe.LoteRps>, RedSky.Infrastructure.NFSe.SPSorocabaNFSe.LoteRps {
        
        public LoteRpsClient() {
        }
        
        public LoteRpsClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LoteRpsClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoteRpsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoteRpsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RedSky.Infrastructure.NFSe.SPSorocabaNFSe.consultarSequencialRpsResponse RedSky.Infrastructure.NFSe.SPSorocabaNFSe.LoteRps.consultarSequencialRps(RedSky.Infrastructure.NFSe.SPSorocabaNFSe.consultarSequencialRpsRequest request) {
            return base.Channel.consultarSequencialRps(request);
        }
        
        public string consultarSequencialRps(string mensagemXml) {
            RedSky.Infrastructure.NFSe.SPSorocabaNFSe.consultarSequencialRpsRequest inValue = new RedSky.Infrastructure.NFSe.SPSorocabaNFSe.consultarSequencialRpsRequest();
            inValue.mensagemXml = mensagemXml;
            RedSky.Infrastructure.NFSe.SPSorocabaNFSe.consultarSequencialRpsResponse retVal = ((RedSky.Infrastructure.NFSe.SPSorocabaNFSe.LoteRps)(this)).consultarSequencialRps(inValue);
            return retVal.consultarSequencialRpsReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RedSky.Infrastructure.NFSe.SPSorocabaNFSe.consultarSequencialRpsResponse> RedSky.Infrastructure.NFSe.SPSorocabaNFSe.LoteRps.consultarSequencialRpsAsync(RedSky.Infrastructure.NFSe.SPSorocabaNFSe.consultarSequencialRpsRequest request) {
            return base.Channel.consultarSequencialRpsAsync(request);
        }
        
        public System.Threading.Tasks.Task<RedSky.Infrastructure.NFSe.SPSorocabaNFSe.consultarSequencialRpsResponse> consultarSequencialRpsAsync(string mensagemXml) {
            RedSky.Infrastructure.NFSe.SPSorocabaNFSe.consultarSequencialRpsRequest inValue = new RedSky.Infrastructure.NFSe.SPSorocabaNFSe.consultarSequencialRpsRequest();
            inValue.mensagemXml = mensagemXml;
            return ((RedSky.Infrastructure.NFSe.SPSorocabaNFSe.LoteRps)(this)).consultarSequencialRpsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RedSky.Infrastructure.NFSe.SPSorocabaNFSe.enviarSincronoResponse RedSky.Infrastructure.NFSe.SPSorocabaNFSe.LoteRps.enviarSincrono(RedSky.Infrastructure.NFSe.SPSorocabaNFSe.enviarSincronoRequest request) {
            return base.Channel.enviarSincrono(request);
        }
        
        public string enviarSincrono(string mensagemXml) {
            RedSky.Infrastructure.NFSe.SPSorocabaNFSe.enviarSincronoRequest inValue = new RedSky.Infrastructure.NFSe.SPSorocabaNFSe.enviarSincronoRequest();
            inValue.mensagemXml = mensagemXml;
            RedSky.Infrastructure.NFSe.SPSorocabaNFSe.enviarSincronoResponse retVal = ((RedSky.Infrastructure.NFSe.SPSorocabaNFSe.LoteRps)(this)).enviarSincrono(inValue);
            return retVal.enviarSincronoReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RedSky.Infrastructure.NFSe.SPSorocabaNFSe.enviarSincronoResponse> RedSky.Infrastructure.NFSe.SPSorocabaNFSe.LoteRps.enviarSincronoAsync(RedSky.Infrastructure.NFSe.SPSorocabaNFSe.enviarSincronoRequest request) {
            return base.Channel.enviarSincronoAsync(request);
        }
        
        public System.Threading.Tasks.Task<RedSky.Infrastructure.NFSe.SPSorocabaNFSe.enviarSincronoResponse> enviarSincronoAsync(string mensagemXml) {
            RedSky.Infrastructure.NFSe.SPSorocabaNFSe.enviarSincronoRequest inValue = new RedSky.Infrastructure.NFSe.SPSorocabaNFSe.enviarSincronoRequest();
            inValue.mensagemXml = mensagemXml;
            return ((RedSky.Infrastructure.NFSe.SPSorocabaNFSe.LoteRps)(this)).enviarSincronoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RedSky.Infrastructure.NFSe.SPSorocabaNFSe.enviarResponse RedSky.Infrastructure.NFSe.SPSorocabaNFSe.LoteRps.enviar(RedSky.Infrastructure.NFSe.SPSorocabaNFSe.enviarRequest request) {
            return base.Channel.enviar(request);
        }
        
        public string enviar(string mensagemXml) {
            RedSky.Infrastructure.NFSe.SPSorocabaNFSe.enviarRequest inValue = new RedSky.Infrastructure.NFSe.SPSorocabaNFSe.enviarRequest();
            inValue.mensagemXml = mensagemXml;
            RedSky.Infrastructure.NFSe.SPSorocabaNFSe.enviarResponse retVal = ((RedSky.Infrastructure.NFSe.SPSorocabaNFSe.LoteRps)(this)).enviar(inValue);
            return retVal.enviarReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RedSky.Infrastructure.NFSe.SPSorocabaNFSe.enviarResponse> RedSky.Infrastructure.NFSe.SPSorocabaNFSe.LoteRps.enviarAsync(RedSky.Infrastructure.NFSe.SPSorocabaNFSe.enviarRequest request) {
            return base.Channel.enviarAsync(request);
        }
        
        public System.Threading.Tasks.Task<RedSky.Infrastructure.NFSe.SPSorocabaNFSe.enviarResponse> enviarAsync(string mensagemXml) {
            RedSky.Infrastructure.NFSe.SPSorocabaNFSe.enviarRequest inValue = new RedSky.Infrastructure.NFSe.SPSorocabaNFSe.enviarRequest();
            inValue.mensagemXml = mensagemXml;
            return ((RedSky.Infrastructure.NFSe.SPSorocabaNFSe.LoteRps)(this)).enviarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RedSky.Infrastructure.NFSe.SPSorocabaNFSe.testeEnviarResponse RedSky.Infrastructure.NFSe.SPSorocabaNFSe.LoteRps.testeEnviar(RedSky.Infrastructure.NFSe.SPSorocabaNFSe.testeEnviarRequest request) {
            return base.Channel.testeEnviar(request);
        }
        
        public string testeEnviar(string mensagemXml) {
            RedSky.Infrastructure.NFSe.SPSorocabaNFSe.testeEnviarRequest inValue = new RedSky.Infrastructure.NFSe.SPSorocabaNFSe.testeEnviarRequest();
            inValue.mensagemXml = mensagemXml;
            RedSky.Infrastructure.NFSe.SPSorocabaNFSe.testeEnviarResponse retVal = ((RedSky.Infrastructure.NFSe.SPSorocabaNFSe.LoteRps)(this)).testeEnviar(inValue);
            return retVal.testeEnviarReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RedSky.Infrastructure.NFSe.SPSorocabaNFSe.testeEnviarResponse> RedSky.Infrastructure.NFSe.SPSorocabaNFSe.LoteRps.testeEnviarAsync(RedSky.Infrastructure.NFSe.SPSorocabaNFSe.testeEnviarRequest request) {
            return base.Channel.testeEnviarAsync(request);
        }
        
        public System.Threading.Tasks.Task<RedSky.Infrastructure.NFSe.SPSorocabaNFSe.testeEnviarResponse> testeEnviarAsync(string mensagemXml) {
            RedSky.Infrastructure.NFSe.SPSorocabaNFSe.testeEnviarRequest inValue = new RedSky.Infrastructure.NFSe.SPSorocabaNFSe.testeEnviarRequest();
            inValue.mensagemXml = mensagemXml;
            return ((RedSky.Infrastructure.NFSe.SPSorocabaNFSe.LoteRps)(this)).testeEnviarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RedSky.Infrastructure.NFSe.SPSorocabaNFSe.consultarLoteResponse RedSky.Infrastructure.NFSe.SPSorocabaNFSe.LoteRps.consultarLote(RedSky.Infrastructure.NFSe.SPSorocabaNFSe.consultarLoteRequest request) {
            return base.Channel.consultarLote(request);
        }
        
        public string consultarLote(string mensagemXml) {
            RedSky.Infrastructure.NFSe.SPSorocabaNFSe.consultarLoteRequest inValue = new RedSky.Infrastructure.NFSe.SPSorocabaNFSe.consultarLoteRequest();
            inValue.mensagemXml = mensagemXml;
            RedSky.Infrastructure.NFSe.SPSorocabaNFSe.consultarLoteResponse retVal = ((RedSky.Infrastructure.NFSe.SPSorocabaNFSe.LoteRps)(this)).consultarLote(inValue);
            return retVal.consultarLoteReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RedSky.Infrastructure.NFSe.SPSorocabaNFSe.consultarLoteResponse> RedSky.Infrastructure.NFSe.SPSorocabaNFSe.LoteRps.consultarLoteAsync(RedSky.Infrastructure.NFSe.SPSorocabaNFSe.consultarLoteRequest request) {
            return base.Channel.consultarLoteAsync(request);
        }
        
        public System.Threading.Tasks.Task<RedSky.Infrastructure.NFSe.SPSorocabaNFSe.consultarLoteResponse> consultarLoteAsync(string mensagemXml) {
            RedSky.Infrastructure.NFSe.SPSorocabaNFSe.consultarLoteRequest inValue = new RedSky.Infrastructure.NFSe.SPSorocabaNFSe.consultarLoteRequest();
            inValue.mensagemXml = mensagemXml;
            return ((RedSky.Infrastructure.NFSe.SPSorocabaNFSe.LoteRps)(this)).consultarLoteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RedSky.Infrastructure.NFSe.SPSorocabaNFSe.consultarAliquotaSimplesNacionalResponse RedSky.Infrastructure.NFSe.SPSorocabaNFSe.LoteRps.consultarAliquotaSimplesNacional(RedSky.Infrastructure.NFSe.SPSorocabaNFSe.consultarAliquotaSimplesNacionalRequest request) {
            return base.Channel.consultarAliquotaSimplesNacional(request);
        }
        
        public string consultarAliquotaSimplesNacional(string cpfResponsavel, string ultimaAtualizacao, string codCid) {
            RedSky.Infrastructure.NFSe.SPSorocabaNFSe.consultarAliquotaSimplesNacionalRequest inValue = new RedSky.Infrastructure.NFSe.SPSorocabaNFSe.consultarAliquotaSimplesNacionalRequest();
            inValue.cpfResponsavel = cpfResponsavel;
            inValue.ultimaAtualizacao = ultimaAtualizacao;
            inValue.codCid = codCid;
            RedSky.Infrastructure.NFSe.SPSorocabaNFSe.consultarAliquotaSimplesNacionalResponse retVal = ((RedSky.Infrastructure.NFSe.SPSorocabaNFSe.LoteRps)(this)).consultarAliquotaSimplesNacional(inValue);
            return retVal.consultarAliquotaSimplesNacionalReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RedSky.Infrastructure.NFSe.SPSorocabaNFSe.consultarAliquotaSimplesNacionalResponse> RedSky.Infrastructure.NFSe.SPSorocabaNFSe.LoteRps.consultarAliquotaSimplesNacionalAsync(RedSky.Infrastructure.NFSe.SPSorocabaNFSe.consultarAliquotaSimplesNacionalRequest request) {
            return base.Channel.consultarAliquotaSimplesNacionalAsync(request);
        }
        
        public System.Threading.Tasks.Task<RedSky.Infrastructure.NFSe.SPSorocabaNFSe.consultarAliquotaSimplesNacionalResponse> consultarAliquotaSimplesNacionalAsync(string cpfResponsavel, string ultimaAtualizacao, string codCid) {
            RedSky.Infrastructure.NFSe.SPSorocabaNFSe.consultarAliquotaSimplesNacionalRequest inValue = new RedSky.Infrastructure.NFSe.SPSorocabaNFSe.consultarAliquotaSimplesNacionalRequest();
            inValue.cpfResponsavel = cpfResponsavel;
            inValue.ultimaAtualizacao = ultimaAtualizacao;
            inValue.codCid = codCid;
            return ((RedSky.Infrastructure.NFSe.SPSorocabaNFSe.LoteRps)(this)).consultarAliquotaSimplesNacionalAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RedSky.Infrastructure.NFSe.SPSorocabaNFSe.consultarNotaTomadaResponse RedSky.Infrastructure.NFSe.SPSorocabaNFSe.LoteRps.consultarNotaTomada(RedSky.Infrastructure.NFSe.SPSorocabaNFSe.consultarNotaTomadaRequest request) {
            return base.Channel.consultarNotaTomada(request);
        }
        
        public string consultarNotaTomada(string mensagemXml) {
            RedSky.Infrastructure.NFSe.SPSorocabaNFSe.consultarNotaTomadaRequest inValue = new RedSky.Infrastructure.NFSe.SPSorocabaNFSe.consultarNotaTomadaRequest();
            inValue.mensagemXml = mensagemXml;
            RedSky.Infrastructure.NFSe.SPSorocabaNFSe.consultarNotaTomadaResponse retVal = ((RedSky.Infrastructure.NFSe.SPSorocabaNFSe.LoteRps)(this)).consultarNotaTomada(inValue);
            return retVal.consultarNotaTomadaReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RedSky.Infrastructure.NFSe.SPSorocabaNFSe.consultarNotaTomadaResponse> RedSky.Infrastructure.NFSe.SPSorocabaNFSe.LoteRps.consultarNotaTomadaAsync(RedSky.Infrastructure.NFSe.SPSorocabaNFSe.consultarNotaTomadaRequest request) {
            return base.Channel.consultarNotaTomadaAsync(request);
        }
        
        public System.Threading.Tasks.Task<RedSky.Infrastructure.NFSe.SPSorocabaNFSe.consultarNotaTomadaResponse> consultarNotaTomadaAsync(string mensagemXml) {
            RedSky.Infrastructure.NFSe.SPSorocabaNFSe.consultarNotaTomadaRequest inValue = new RedSky.Infrastructure.NFSe.SPSorocabaNFSe.consultarNotaTomadaRequest();
            inValue.mensagemXml = mensagemXml;
            return ((RedSky.Infrastructure.NFSe.SPSorocabaNFSe.LoteRps)(this)).consultarNotaTomadaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RedSky.Infrastructure.NFSe.SPSorocabaNFSe.consultarNotaResponse RedSky.Infrastructure.NFSe.SPSorocabaNFSe.LoteRps.consultarNota(RedSky.Infrastructure.NFSe.SPSorocabaNFSe.consultarNotaRequest request) {
            return base.Channel.consultarNota(request);
        }
        
        public string consultarNota(string mensagemXml) {
            RedSky.Infrastructure.NFSe.SPSorocabaNFSe.consultarNotaRequest inValue = new RedSky.Infrastructure.NFSe.SPSorocabaNFSe.consultarNotaRequest();
            inValue.mensagemXml = mensagemXml;
            RedSky.Infrastructure.NFSe.SPSorocabaNFSe.consultarNotaResponse retVal = ((RedSky.Infrastructure.NFSe.SPSorocabaNFSe.LoteRps)(this)).consultarNota(inValue);
            return retVal.consultarNotaReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RedSky.Infrastructure.NFSe.SPSorocabaNFSe.consultarNotaResponse> RedSky.Infrastructure.NFSe.SPSorocabaNFSe.LoteRps.consultarNotaAsync(RedSky.Infrastructure.NFSe.SPSorocabaNFSe.consultarNotaRequest request) {
            return base.Channel.consultarNotaAsync(request);
        }
        
        public System.Threading.Tasks.Task<RedSky.Infrastructure.NFSe.SPSorocabaNFSe.consultarNotaResponse> consultarNotaAsync(string mensagemXml) {
            RedSky.Infrastructure.NFSe.SPSorocabaNFSe.consultarNotaRequest inValue = new RedSky.Infrastructure.NFSe.SPSorocabaNFSe.consultarNotaRequest();
            inValue.mensagemXml = mensagemXml;
            return ((RedSky.Infrastructure.NFSe.SPSorocabaNFSe.LoteRps)(this)).consultarNotaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RedSky.Infrastructure.NFSe.SPSorocabaNFSe.cancelarResponse RedSky.Infrastructure.NFSe.SPSorocabaNFSe.LoteRps.cancelar(RedSky.Infrastructure.NFSe.SPSorocabaNFSe.cancelarRequest request) {
            return base.Channel.cancelar(request);
        }
        
        public string cancelar(string mensagemXml) {
            RedSky.Infrastructure.NFSe.SPSorocabaNFSe.cancelarRequest inValue = new RedSky.Infrastructure.NFSe.SPSorocabaNFSe.cancelarRequest();
            inValue.mensagemXml = mensagemXml;
            RedSky.Infrastructure.NFSe.SPSorocabaNFSe.cancelarResponse retVal = ((RedSky.Infrastructure.NFSe.SPSorocabaNFSe.LoteRps)(this)).cancelar(inValue);
            return retVal.cancelarReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RedSky.Infrastructure.NFSe.SPSorocabaNFSe.cancelarResponse> RedSky.Infrastructure.NFSe.SPSorocabaNFSe.LoteRps.cancelarAsync(RedSky.Infrastructure.NFSe.SPSorocabaNFSe.cancelarRequest request) {
            return base.Channel.cancelarAsync(request);
        }
        
        public System.Threading.Tasks.Task<RedSky.Infrastructure.NFSe.SPSorocabaNFSe.cancelarResponse> cancelarAsync(string mensagemXml) {
            RedSky.Infrastructure.NFSe.SPSorocabaNFSe.cancelarRequest inValue = new RedSky.Infrastructure.NFSe.SPSorocabaNFSe.cancelarRequest();
            inValue.mensagemXml = mensagemXml;
            return ((RedSky.Infrastructure.NFSe.SPSorocabaNFSe.LoteRps)(this)).cancelarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        RedSky.Infrastructure.NFSe.SPSorocabaNFSe.consultarNFSeRpsResponse RedSky.Infrastructure.NFSe.SPSorocabaNFSe.LoteRps.consultarNFSeRps(RedSky.Infrastructure.NFSe.SPSorocabaNFSe.consultarNFSeRpsRequest request) {
            return base.Channel.consultarNFSeRps(request);
        }
        
        public string consultarNFSeRps(string mensagemXml) {
            RedSky.Infrastructure.NFSe.SPSorocabaNFSe.consultarNFSeRpsRequest inValue = new RedSky.Infrastructure.NFSe.SPSorocabaNFSe.consultarNFSeRpsRequest();
            inValue.mensagemXml = mensagemXml;
            RedSky.Infrastructure.NFSe.SPSorocabaNFSe.consultarNFSeRpsResponse retVal = ((RedSky.Infrastructure.NFSe.SPSorocabaNFSe.LoteRps)(this)).consultarNFSeRps(inValue);
            return retVal.consultarNFSeRpsReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<RedSky.Infrastructure.NFSe.SPSorocabaNFSe.consultarNFSeRpsResponse> RedSky.Infrastructure.NFSe.SPSorocabaNFSe.LoteRps.consultarNFSeRpsAsync(RedSky.Infrastructure.NFSe.SPSorocabaNFSe.consultarNFSeRpsRequest request) {
            return base.Channel.consultarNFSeRpsAsync(request);
        }
        
        public System.Threading.Tasks.Task<RedSky.Infrastructure.NFSe.SPSorocabaNFSe.consultarNFSeRpsResponse> consultarNFSeRpsAsync(string mensagemXml) {
            RedSky.Infrastructure.NFSe.SPSorocabaNFSe.consultarNFSeRpsRequest inValue = new RedSky.Infrastructure.NFSe.SPSorocabaNFSe.consultarNFSeRpsRequest();
            inValue.mensagemXml = mensagemXml;
            return ((RedSky.Infrastructure.NFSe.SPSorocabaNFSe.LoteRps)(this)).consultarNFSeRpsAsync(inValue);
        }
    }
}
